/**
 * @author xiaoping
 * @email edwardhjp@gmail.com
 * @create date 2018-04-11 09:38:52
 * @modify date 2018-04-11 09:38:52
 * @desc [wx不需要promise化的列表]
*/

module.exports = [
  'onSocketOpen',
  'onSocketMessage',
  'onSocketError',
  'onSocketClose',
  'stopRecord',
  'getRecorderManager',
  'pauseVoice',
  'stopVoice',
  'pauseBackgroundAudio',
  'seekBackgroundAudio',
  'stopBackgroundAudio',
  'onBackgroundAudioPlay',
  'onBackgroundAudioPause',
  'onBackgroundAudioStop',
  'getBackgroundAudioManager',
  'createAudioContext',
  'createInnerAudioContext',
  'createVideoContext',
  'createCameraContext',
  'createLivePlayerContext',
  'createLivePusherContext',
  'setStorageSync',
  'getStorageSync',
  'getStorageInfoSync',
  'removeStorageSync',
  'clearStorageSync',
  'createMapContext',
  'getSystemInfoSync',
  'canIUse',
  'onNetworkStatusChange',
  'onAccelerometerChange',
  'onCompassChange',
  'onBluetoothAdapterStateChange',
  'onBluetoothDeviceFound',
  'onBLEConnectionStateChange',
  'onBLECharacteristicValueChange',
  'onBeaconUpdate',
  'onBeaconServiceChange',
  'onUserCaptureScreen',
  'onHCEMessage',
  'onGetWifiList',
  'onWifiConnected',
  'hideToast',
  'hideLoading',
  'showNavigationBarLoading',
  'hideNavigationBarLoading',
  'navigateBack',
  'createAnimation',
  'pageScrollTo',
  'createCanvasContext',
  'createContext',
  'drawCanvas',
  'stopPullDownRefresh',
  'createSelectorQuery',
  'createIntersectionObserver',
  'getExtConfigSync',
  'getUpdateManager',
  'createWorker'
]
